### ISSUE TITLE
Problem with headless charakter in photomode

### ISSUE THREAD

**Issue by MrBilL61** [striderxfossility/tppmodcyberpunk#13]
Hello, I'm using TPP mod in combination with IGCS camera to take better angles in mid-dialogues scenes. It works quite good, but in the latest version I've got something like this:
![photomode_12022021_155538](https://user-images.githubusercontent.com/60363662/107784956-4f481c00-6d4c-11eb-9072-4a47bbdf134e.png)
I tried to switch back and forth between FPP and TPP but it doesn't work

**Comment by pawkropl** [comment]
Sadly "scenes pull" doesn't fix the problem. The picture was taken after applying this pull.
