### ISSUE TITLE
27 & 27.1: Can't pick up a quest item, even in first person mode

### ISSUE THREAD

**Issue by Guerlot** [striderxfossility/tppmodcyberpunk#16]
Hi, 

Using version 27.1:

While doing the quest Automatic Love, early in the quest where I need to speak with Judy at the Afterlife and where I need to pick up Evelyn's cigarettes case.

First I had to be a little far away from Judy to get the dialogue prompt show up. then, once she tells me to get the cigarette case, I just couldn't pick it up, even in first person mode (note that I did enter the Afterlife in 1st person). Tried switching back and forth from 1st & 3rd, no luck. Saved the game, reloaded the game, no luck. 

I reverted back to version 27: Same thing
I reverted back to version 25: No issue. So looks like this was introduced in 27, suspecting when you : "_Added better interactions (doors not working yet), but items and talking to mission player do work_"

I will keep a save game there, if you would like me to test it.

Thank you so much for this mod!!

**Comment by striderxfossility** [comment]
Jump for now

**Comment by ThanosAtha** [comment]
FreeFly mod solve it for me..
