### ISSUE TITLE
v is still headless in photo mode

### ISSUE THREAD

**Issue by spudomie** [striderxfossility/tppmodcyberpunk#23]
I know this issue was submitted and resolved a few days ago, but despite downloading every new version of TPP released since the issue was apparently fixed, my V's head continues to be invisible when I use the combination of TPP, photo mode, and the injectable external camera in cutscenes. Not sure what the issue is because I've been testing swapping out any mods that could be causing the issue separate from TPP, but nothing seems to work.
![photomode_23022021_184936](https://user-images.githubusercontent.com/79555226/108940374-18092300-7608-11eb-86ad-fe8d80b507cb.png)

**Comment by striderxfossility** [comment]
Greetings, did you download the latest version? not from nexus but from here?

**Comment by spudomie** [comment]
Yes, I'm currently operating on V35 and I continue to have this issue!

**Comment by DorianSoloviev** [comment]
Same here... someone know what is the problem? :<

**Comment by striderxfossility** [comment]
It looks like you have the same issue as [https://github.com/striderxfossility/tppmodcyberpunk/issues/24](url).
so my guess is a body mod distort the rig. 

if thats the case i wont be solving others mods problems just yet, need to fixed and enchant the current own problems of the mod.

**Comment by spudomie** [comment]
I actually took out all the mods I use aside from TPP and CET to see if a mod was causing the issue and my V continued to be headless even without the body mod I use. However, I installed V11 of TPP from Nexus on a whim because that seemed to be the last version where V's head showed up in cutscenes, and V11 works perfectly. So I'm not totally sure what the issue is.
