### ISSUE TITLE
Weird face bug

### ISSUE THREAD

**Issue by arkillik** [striderxfossility/tppmodcyberpunk#24]
![Screenshot (273)](https://user-images.githubusercontent.com/79728107/109364835-4a5b9000-7855-11eb-8ed7-1403734eee6d.png)
![Screenshot (274)](https://user-images.githubusercontent.com/79728107/109364841-50517100-7855-11eb-833d-6249130bc5b4.png)
Not sure why it happened, it was fine in first person during dialog, then when I switched to third person I got what is in the images.

**Comment by striderxfossility** [comment]
What kinds of mods are you using? Kind of a first to see this

**Comment by arkillik** [comment]
> What kinds of mods are you using? Kind of a first to see this

Mainly clothing mods, an advertisements replacer, and a some body mods. I suppose it could be the body mods or just the game in general.

**Comment by striderxfossility** [comment]
If you use Spawn body mod, it would be fine, because that dude is also using my mod, other body mods i dont know. If they are messing up the rig it could be possible.
