### ISSUE TITLE
Can we fix the 2seconds head-off issue when switching the mod? 

### ISSUE THREAD

**Issue by ThanosAtha** [striderxfossility/tppmodcyberpunk#25]

**Comment by ThanosAtha** [comment]
It would be good!

**Comment by striderxfossility** [comment]
And would you suggest it i do fix it? because there is a load delay thats for sure, and i cant fix that. see enter photomode, there is also a load delay spawing all the items.

**Comment by striderxfossility** [comment]
This is present in upcoming update V68
