### ISSUE TITLE
Nothing happens when talking to NPC

### ISSUE THREAD

**Issue by just-nkt** [striderxfossility/tppmodcyberpunk#26]
![Untitled](https://user-images.githubusercontent.com/25139259/111053362-c4c90a00-8428-11eb-963a-fa9bbf29a220.png)
After going into a third person mode and then switching back to a first person mode, you can no longer talk to random NPCs by pressing F.
I tried deleting basegame_interaction-fix.archive but the problem still persists.

**Comment by striderxfossility** [comment]
Yes know issue

**Comment by striderxfossility** [comment]
Fixed in upcoming update V68
