### ISSUE TITLE
worries it works but disarmed.

### ISSUE THREAD

**Issue by piratair** [striderxfossility/tppmodcyberpunk#27]
Hello ,

First of all thank you for this mod, at home after following all the explanations, I gave a function to several keys.
To appear the mode to the 3rd person, to zoom and dezoomer, but I have a problem, it does not function only if I am disarmed?
If I have a weapon between hands more view in 3 ° person, I have to remove my weapon otherwise my character returns first.
I was so happy to play the 3rd person, to know that it was possible but it stops that there, I would like a little help, I thank you in advance.
cordially

**Comment by striderxfossility** [comment]
Greetings, just open the debug menu, press the button weaponOverride, then you can have 3rd person while weapon equipped.
