### ISSUE TITLE
Think TTP is broken today. New CET update and Cyberpunk Patch 1.2 today

### ISSUE THREAD

**Issue by darksharke** [striderxfossility/tppmodcyberpunk#28]
Installed Patch 1.2
Installed new version CET issued today for Patch 1.2
Reinstalled TPP (v27) when it did not work on first login

cannot get TPP third person mod to activate with key bind set, even though re-installed, maybe doesn't work with new CET? everything else working that depends on CET, mods including Appearance Menu, FreeFly, TeleportGateway etc all fine, but only TPP seems to be a casualty... Console recognises it as a mod installed, and lets me bind the key but then the key does not activate the TPP view in game...looks like the new CET changed things again so we need a new version of the TPP mod, thanks

**Comment by striderxfossility** [comment]
Its updated
