### ISSUE TITLE
Swapped character heads are now invisible

### ISSUE THREAD

**Issue by scubachrist** [striderxfossility/tppmodcyberpunk#30]
Prior to 1.2 I used this mod for the majority of my playthrough along with mods that would swap V's appearance such as Alvarix's [Moxes](https://www.nexusmods.com/cyberpunk2077/mods/1974) Girl Swap. Unfortunately V38 now makes V's head invisible if I use anything other than a vanilla V appearance. Can this be fixed?

**Comment by striderxfossility** [comment]
See debug menu, click the button of headmodel or something
