### ISSUE TITLE
Lose 'wasd' movement after camera changes

### ISSUE THREAD

**Issue by fredd2021** [striderxfossility/tppmodcyberpunk#31]
After 1.21 there seems to be a lack of keyboard input for 'wasd' movement after going 3rd person and changing pov.  You can open inventory and journal but you can't move.  The problem is occasional, it's not all the time, but it has happened 5-6 times in 2 hours.

And thanks for the mod by the way, in my opinion it makes the game playable.

**Comment by striderxfossility** [comment]
Yes its a known bug, try to change the camera while not moving. it bugs out when moving and simultanisly changing /zoomin out with camera.

**Comment by striderxfossility** [comment]
This is fixed in upcoming V68
