### ISSUE TITLE
Men V running in thierd person is really weird and scary also in patch 1.31 V is no longer bald with hat armor.

### ISSUE THREAD

**Issue by Gh0stCz** [striderxfossility/tppmodcyberpunk#38]
Like V can be bald but i try activete TPP 10 times and in 9 try she have hairs using hide armor mod.

**Comment by striderxfossility** [comment]
wait, you mean you can have third person active and you can see your hat on the character?

**Comment by Gh0stCz** [comment]
Not hat i am using hide armor and pigtails hair mode to see hairs
