### ISSUE TITLE
E3 2018 mod doesn't work with JB - TPP

### ISSUE THREAD

**Issue by JustaPosta** [striderxfossility/tppmodcyberpunk#6]
Hello, so I'm having an issue with this mod. I'm using https://www.nexusmods.com/cyberpunk2077/mods/1517?tab=posts
and everytime I go into 3rd person my characters head is invisible is there a way to fix this? Or maybe you could work with the mod creator to create a fix? Thanks!

**Comment by striderxfossility** [comment]
Yeah, problem is that the mods of the head replacement, is actually a mod that make the head invisible, and they used public hair or whatever that includes the new head, so i cant fix it, unless they actually replace the main head with the new head, then it wont be a problem

**Comment by striderxfossility** [comment]
i investigate it, the mod author should just replace the head.
